### ISSUE TITLE
Fix Makefile issues for the merge from max/sh into dev

### ISSUE THREAD

**Issue by liaminchi** [cmsc22000-project-2018/fulltext#105]
Fixing makefile issues in the max/sh branch to conform with the new makefile standards

**Comment by RuolinZheng08** [comment]
Hi Liam! Since you are working on this could you please put test_trie.c into tests/Makefile and see if the linking is normal? I have trouble compiling this on my side. Thanks!

**Comment by liaminchi** [comment]
@RuolinZheng08 The mtrie test seems to work on the dev branch! I am closing this issue. 27383000065b8d46bff286c56ca8319665365ac5
