### ISSUE TITLE
Write Unit Tests for parse_file_buffered in search.c

### ISSUE THREAD

**Issue by RuolinZheng08** [cmsc22000-project-2018/fulltext#106]
As this is the crucial component of the fulltext program, extensive test cases will be written and thus this is listed as a separated issue from find_match in search.c

**Comment by mbronckers** [comment]
A few unit tests will suffice I think, the real challenge is to test end-to-end functionality --> integration testing.

**Comment by RuolinZheng08** [comment]
Unit tests will be written for the trie version instead.
