### ISSUE TITLE
Fix wrap-around issue in find()

### ISSUE THREAD

**Issue by mbronckers** [cmsc22000-project-2018/fulltext#124]
Summary: 
-  Fix the wrap-around bug when traversing through list of matches using `next` and `prev`

**Comment by MoldyAppleJuice** [comment]
[e001691] to fix prev: 
index was previously determined with 
`index = ((index - 1) + list_size(&matches)) / list_size(&matches);`

but to properly calculate the wraparound index, it should be
`index = ((index - 1) + list_size(&matches)) % list_size(&matches);`

**Comment by mbronckers** [comment]
Fixed
