### ISSUE TITLE
Create search and match related functions for batch mode

### ISSUE THREAD

**Issue by liaminchi** [cmsc22000-project-2018/fulltext#133]
Will work on implementing the batch mode.
- Search the entire for matches
- Add into match lists
- And other related things

**Comment by RuolinZheng08** [comment]
I guess we will just load the file path like:
ftsh> find <filepath>
then load fp into a string array, then to a trie
then we call the same functions in search.c

**Comment by RuolinZheng08** [comment]
Implemented ftsh utilities to load batchfile specified by -b flag
Read the FILE *ptr into a string array with parser.c
Turn the string array into a trie with trie_from_strarray in trie.c
Search will be handled in future issues.
