### ISSUE TITLE
Writing search algorithm - Aho Corasick in search.c

### ISSUE THREAD

**Issue by MoldyAppleJuice** [cmsc22000-project-2018/fulltext#46]

**Comment by MoldyAppleJuice** [comment]
should have updated this a while ago, but since we are not implementing aho corasick in sprint 3 (only the inefficient search algorithm), this task isn't useful for sprint 3. will probably move to sprint 4.

**Comment by RuolinZheng08** [comment]
As trie.c is working, we will start implementing Aho Corasick, the efficient search algorithm in Sprint 4.

**Comment by RuolinZheng08** [comment]
Decided this is not necessary.
